name: Render all models
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          path: main
      - uses: actions/checkout@v2
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Get OpenSCAD
        run: |
          sudo add-apt-repository ppa:openscad/releases
          sudo apt-get update
          sudo apt-get install openscad
      - name: Export previews
        run: |
          cd ~/work/models/models/main
          mkdir -p previews
          for model in *.scad; do /usr/bin/xvfb-run --auto-servernum openscad "$model" --hardwarnings --imgsize 1920,1080 --autocenter --viewall -o "./previews/${model%.scad}.png" --preview=throwntogether; done
      - name: Export renders
        run: |
          cd ~/work/models/models/main
          mkdir -p renders
          for model in *.scad; do /usr/bin/xvfb-run --auto-servernum openscad $model --hardwarnings -o "./renders/${model%.scad}.3mf" -o "./renders/${model%.scad}.amf" -o "./renders/${model%.scad}.off" -o "./renders/${model%.scad}.stl"; done
      - name: Add previews to wiki
        run: |
          cd ~/work/models/models/wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -r ~/work/models/models/main/previews .
          git add previews
          git commit -m "Update previews" || echo "No preview changes to commit"
      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@v0.6.0
        with:
          repository: ${{github.repository}}.wiki
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: /home/runner/work/models/models/wiki
      - name: Create release with renders
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Rendered models"
          files: |
            /home/runner/work/models/models/main/renders/*
