name: Render all models
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          path: main
      - uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: wiki
      - name: Get OpenSCAD
        run: |
          sudo apt-get update
          sudo apt-get install openscad
      - name: Export previews
        run: |
          cd ~/work/models/models/main
          mkdir -p previews
          for model in *.scad; do echo $model && /usr/bin/xvfb-run --auto-servernum openscad "$model" --hardwarnings --imgsize 1920,1080 --autocenter --viewall -o "./previews/${model%.scad}.png" --preview=throwntogether; done
      - name: Export renders
        run: |
          cd ~/work/models/models/main
          mkdir -p renders
          for model in *.scad; do echo $model && /usr/bin/xvfb-run --auto-servernum openscad $model --hardwarnings -o "./renders/${model%.scad}.3mf" -o "./renders/${model%.scad}.amf" -o "./renders/${model%.scad}.off" -o "./renders/${model%.scad}.stl"; done
      - name: Update wiki
        run: |
          cd ~/work/models/models/wiki
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          echo "Welcome to the models wiki! Here you can see previews and download rendered models." > Home.md
          for model in ~/work/models/models/main/*.scad;
            do echo "## $(basename $model .scad |  sed -e 's/_/ /g' -e 's/\b\(.\)/\u\1/g')" >> Home.md
            echo "Downloads: [STL](https://github.com/sameer/models/releases/download/latest/$(basename $model .scad).stl)" >> Home.md
            echo " | [3MF](https://github.com/sameer/models/releases/download/latest/$(basename $model .scad).3mf)" >> Home.md
            echo " | [AMF](https://github.com/sameer/models/releases/download/latest/$(basename $model .scad).amf)" >> Home.md
            echo " | [OFF](https://github.com/sameer/models/releases/download/latest/$(basename $model .scad).off)" >> Home.md
            echo "### Preview" >> Home.md
            echo "![OpenScad preview](previews/$(basename $model .scad).png)" >> Home.md
            echo "### Printed" >> Home.md
            echo "![Printed model in action, if available](prints/$(basename $model .scad).jpg)" >> Home.md
          done
          git add Home.md
          cp -r ~/work/models/models/main/previews .
          git add previews
          git commit -m "Update wiki" || echo "No wiki changes to commit"
      - name: Push changes to wiki repo
        uses: ad-m/github-push-action@v0.8.0
        with:
          repository: ${{github.repository}}.wiki
          branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: /home/runner/work/models/models/wiki
      - name: Create release with renders
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Rendered models"
          files: |
            /home/runner/work/models/models/main/renders/*
